# Eureka-consumer config
spring:
  application:
    name: myava-eureka-consumer
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    sender:
      type: kafka
    service:
      name: ${spring.application.name}
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.application.name}
      enable-auto-commit: false
      #auto-commit-interval: 5000MS
      auto-offset-reset: latest
      #max-poll-records: 500
      properties:
        max.poll.interval.ms: 300000
#    listener:
#      type: batch
#      concurrency: 4
#      ack-mode: manual-immediate
    
server: 
  port: 8081
#  servlet:
#    context-path: /consumer

swagger:
  title: API接口文档
  description: API描述
  version: 1.0
  base-package: com.myava.eureka.consumer.controller

eureka:
  instance:
    prefer-ip-address: true
    #hostname: localhost
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    # 是否注册实例到eureka注册中心，默认true
    register-with-eureka: false
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://eureka-server1:7001/eureka/,http://eureka-server2:7002/eureka/,http://eureka-server3:7003/eureka/

# 配置服务负载均衡策略
#myava-eureka-provider.ribbon.NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

feign.hystrix.enabled: true
# Ribbon超时时间和Hystrix超时时间决定Feign超时时间
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 1000
  # 非GET请求，默认连接超时才会重试，即ConnectTimeout
#  MaxAutoRetries: 0                # 同一台实例最大重试次数,不包括首次调用
#  MaxAutoRetriesNextServer: 1      # 重试负载均衡其他的实例最大重试次数,不包括首次调用
#  OkToRetryOnAllOperations: false  # 是否所有操作都重试，默认false 
hystrix.command.default.execution:
  isolation:
    thread.timeoutInMilliseconds: 8000 #默认是1秒，大于ReadTimeout+ConnectTimeout
  timeout.enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
      